### ISSUE TITLE
Allocation and deallocation not consistent

### ISSUE THREAD

**Issue by Yao1993** [GGEMS/ggems#5]
When allocating voxelized_volume_,  ```T``` is  a template parameter.
https://github.com/GGEMS/ggems/blob/f4520797dc2d81c18fe844a0300088a0d5b49da4/include/GGEMS/geometries/GGEMSVolumeCreatorManager.hh#L252-L263

When deallocating voxelized_volume_, ```T``` is a variable (```__constant GGfloat T = 0.001f; /*!< Tesla 0.001*megavolt*ns/mm2 */```).
https://github.com/GGEMS/ggems/blob/f4520797dc2d81c18fe844a0300088a0d5b49da4/src/geometries/GGEMSVolumeCreatorManager.cc#L74-L86

**Comment by didierbenoit** [comment]
Well done, I do the modification as soon as possible in the devs branch.
Thank you
