### ISSUE TITLE
String subscript out of range

### ISSUE THREAD

**Issue by Yao1993** [GGEMS/ggems#7]
The release version of example 2 works fine, but the debug version of example 2 throw a string subscript out of range error.
I find that `GGEMSTextReader::SkipComment`  cannot handle empty string properly. When `line` is empty, `line.find_first_not_of("\t ")` returns the maximum value of `size_t`. So, `line[line.find_first_not_of("\t ")]`  throw a string subscript out of range error.
https://github.com/GGEMS/ggems/blob/f4520797dc2d81c18fe844a0300088a0d5b49da4/src/io/GGEMSTextReader.cc#L131-L140

**Comment by didierbenoit** [comment]
Hi,
Ok, I will fix this problem in the next commit on devs branch.
Thank you
Didier
